In [1]:
# Importamos liberarías

import pandas as pd 
import numpy as np

In [8]:
df_ventas = pd.read_csv("ventas.csv", index_col=0)

df_ventas.head()

           ID_Producto Fecha_Venta  Cantidad  Total
ID_Cliente
723                 A1  2023-11-22         2  17.98
498                 C3  2023-11-21         1   5.49
121                 D4  2023-11-20         3  32.97
885                L12  2023-11-19         1   6.49
347                Q17  2023-11-18         2   7.98

In [7]:
df_productos = pd.read_csv("productos.csv", index_col=0)

df_productos.head()

ParserError: Error tokenizing data. C error: Expected 7 fields in line 9, saw 9

In [10]:
df_clientes = pd.read_csv("clientes.csv", index_col=0)

df_clientes.head()

,first_name,last_name,email,gender,City,Country,Address
id,,,,,,,
1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,"Hospitalet De Llobregat, L'",Spain,9289 Merry Circle